# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/test_manifest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/test_manifest.proto\x12\x08\x62igspicy\"j\n\x10\x44\x65layComputation\x12\x1b\n\x13spice_variable_name\x18\x01 \x01(\t\x12\x14\n\x0ctrigger_node\x18\x02 \x01(\t\x12\x13\n\x0btarget_node\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\x01\"k\n\x0bMeasurement\x12\x13\n\x0btarget_node\x18\x01 \x01(\t\x12\x1b\n\x13spice_variable_name\x18\x02 \x01(\t\"*\n\x04Type\x12\x0b\n\x07VOLTAGE\x10\x00\x12\x0b\n\x07\x43URRENT\x10\x01\x12\x08\n\x04TIME\x10\x02\"\xc4\x03\n\x0eLinearAnalysis\x12\x19\n\x11spice_source_file\x18\x01 \x01(\t\x12\x1a\n\x12\x64\x65sign_region_name\x18\x02 \x01(\t\x12\x34\n\ranalysis_type\x18\x03 \x01(\x0e\x32\x1d.bigspicy.LinearAnalysis.Type\x12\x36\n\nsweep_type\x18\x04 \x01(\x0e\x32\".bigspicy.LinearAnalysis.SweepType\x12\x15\n\rstart_freq_hz\x18\x05 \x01(\x01\x12\x14\n\x0cstop_freq_hz\x18\x06 \x01(\x01\x12\x12\n\nnum_points\x18\x07 \x01(\x04\x12\x0c\n\x04tags\x18\x14 \x03(\t\x12,\n\x05ports\x18\x15 \x03(\x0b\x32\x1d.bigspicy.LinearAnalysis.Port\x1aG\n\x04Port\x12\x0e\n\x06number\x18\x01 \x01(\x04\x12\x0c\n\x04node\x18\x02 \x01(\t\x12!\n\x19generating_impedance_ohms\x18\x03 \x01(\x01\"\"\n\x04Type\x12\x05\n\x01Y\x10\x00\x12\x05\n\x01Z\x10\x01\x12\x05\n\x01S\x10\x02\x12\x05\n\x01H\x10\x03\"#\n\tSweepType\x12\n\n\x06LINEAR\x10\x00\x12\n\n\x06\x44\x45\x43\x41\x44\x45\x10\x01\"\xd2\x01\n\x11TransientAnalysis\x12\x19\n\x11spice_source_file\x18\x01 \x01(\t\x12\x1a\n\x12\x64\x65sign_region_name\x18\x02 \x01(\t\x12\x13\n\x0bmodule_name\x18\x03 \x01(\t\x12+\n\x0cmeasurements\x18\x0b \x03(\x0b\x32\x15.bigspicy.Measurement\x12\x36\n\x12\x64\x65lay_computations\x18\x0c \x03(\x0b\x32\x1a.bigspicy.DelayComputation\x12\x0c\n\x04tags\x18\x14 \x03(\t\"z\n\x0cTestManifest\x12\x37\n\x12transient_analyses\x18\x01 \x03(\x0b\x32\x1b.bigspicy.TransientAnalysis\x12\x31\n\x0flinear_analyses\x18\x02 \x03(\x0b\x32\x18.bigspicy.LinearAnalysisb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.test_manifest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DELAYCOMPUTATION._serialized_start=39
  _DELAYCOMPUTATION._serialized_end=145
  _MEASUREMENT._serialized_start=147
  _MEASUREMENT._serialized_end=254
  _MEASUREMENT_TYPE._serialized_start=212
  _MEASUREMENT_TYPE._serialized_end=254
  _LINEARANALYSIS._serialized_start=257
  _LINEARANALYSIS._serialized_end=709
  _LINEARANALYSIS_PORT._serialized_start=565
  _LINEARANALYSIS_PORT._serialized_end=636
  _LINEARANALYSIS_TYPE._serialized_start=638
  _LINEARANALYSIS_TYPE._serialized_end=672
  _LINEARANALYSIS_SWEEPTYPE._serialized_start=674
  _LINEARANALYSIS_SWEEPTYPE._serialized_end=709
  _TRANSIENTANALYSIS._serialized_start=712
  _TRANSIENTANALYSIS._serialized_end=922
  _TESTMANIFEST._serialized_start=924
  _TESTMANIFEST._serialized_end=1046
# @@protoc_insertion_point(module_scope)
